<h1><a id='site_name' href='{$display_settings.public_dir}'>{$site_name}</a></h1>
<h2 id='mottoline'>The beast spawned of Al Gore, pluralized by George Bush.</h2>

<p><img height='30' width='28' src='{$display_settings.public_dir}/resources/images/o.jpg' alt='O' />nce upon a time, the world came together to cast down petty tyranny. Humanity itself struck a blow against the Agents of Evil on the beaches of Normandy, battled it back through Italy, stood on the banks of the river Rhine, and finally walked the streets of Berlin. Peace and prosperity followed for many a year, and humanity has not known an event so terrible since.</p>
<p>But alas. Peace could never last forever. Humanity suffers from a fatal flaw; the greed of the individual. It matters little how charitable and good the collective is, for the individual can undo our best efforts with the stroke of a key. Corporate empires have grown weary of boardroom battles, desiring the profits that come only with a human sacrifice. In their arrogance, the Americans have tilted the world back towards darkness unknown to all but the eldest.</p>
<p>Despite it all, We exist. Forged in the calm by nobel prize winner Al Gore, pluralized by our Magnificent Leader George Bush. We, the collective body of the network, know no bloodshed. An immeterial legion with no loyalty, no nationality, no race, and no religion. We are anonymous; we are your John Smith and Jane Doe; we are your best friend; we are you yourself.</p>
<p>We are not entirely powerless. Where We go, we build and share. Software, encyclopedias, datasets, maps, photographs, music, pictures, funds, flowers, encouragement and criticism - all that is immeterial is ours to give and give. We claim no lives, and Our hands are clean of Human blood.</p>
<p>Afghani blood. Iraqi blood. American blood. British blood. Iranian blood. Israeli blood. Palestinian blood. Lebanese blood. Syrian blood. Canadian blood. In creating our form, we have spilled not one precious drop of it.</p>
<p>These Internets are Ours. They are commanded by no individual, they can be stopped by no individual. They are godless, but it matter little; We are a more benevolent and beautiful God than any individual can aspire to.</p>
<p>Welcome, brother.</p>
